### ISSUE TITLE
Add usage info collection with devs permission

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-shell#306] opened 2020-04-03 17:23 UTC
We want to collect usage of the near shell to improve our products and figure out high level product metrics.

The flow should be post installation, we ask shell users if they would opt in to provide anonymized statistics of their usage. Can store their decision in `~/.neardev/config.json`.

If yes, we want to collect:
 - overall activations (e.g. summary of usage and session attribution?)
 - used networks (local vs devnet/betanet/testnet)
 - anything else? @potatodepaulo 

CC: @kcole16 for Amplitude

Also before fully rolling out, let's confirm with current developers that the language and usage info collected matches their expectations.

**Comment by amgando** [comment] 2020-04-03 17:30
resurfacing Gatsby as a best in class example

https://www.gatsbyjs.org/docs/telemetry/

**Comment by janedegtiareva** [comment] 2020-05-15 16:56
Do we want to add any more features? Can we close the issue at this point?

**Comment by vgrichina** [comment] 2020-05-19 06:30
> Do we want to add any more features? Can we close the issue at this point?

We've discussed in Slack that only interactive commands should ask for opt-in, fixed this here https://github.com/near/near-shell/pull/376

After digging into it I think I have better understanding of what we should add (in order of relative priorities):

- [ ] Provide command line option to opt-in / opt-out
- [ ] Include info on which platform event comes from. I mean GitPod vs CLI (not sure if OS is automatically tracked by mixpanel, but if not – we need it too).
- [ ] Report events even when there are errors (this is very interesting info for debugging at scale). Can be supplemented by some error tracking solution like http://getsentry.com.
- [ ] Connect session to web (e.g. when logging in to wallet)
- [ ] Connect sessions between different GitPod instances (not sure what's best way to approach this 
- [ ] Provide info necessary to connect with on-chain data (like accountId, etc). This might need discussion as doesn't really fall into `We only collect which commands are run via an anonymous identifier.`, though generally should be fine with opt-in (as long as user is informed).

I also have a concern around having to track both start and end events manually for every command. This seems pretty error prone long term (easy to forget to send end event, use wrong identifier while copy-pasting boilerplate, etc).

Is there any reason to not do it automatically for every command? Similar to how @kcole16  has implemented it in wallet https://github.com/near/near-wallet/blob/fb8f25ed17dbb49a662cbf3b6c10e3052b238827/src/middleware/index.js#L42 we just have a whitelist of Redux actions, but other than that they are logged automatically. Fr shell don't even need blacklist – Redux actions are just too noisy.

**Comment by vgrichina** [comment] 2020-05-19 22:58
@potatodepaulo I think we might need to pull separate issues with different priorities. 

> Provide command line option to opt-in / opt-out
> Include info on which platform event comes from. I mean GitPod vs CLI (not sure if OS is automatically tracked by mixpanel, but if not – we need it too).
> Report events even when there are errors (this is very interesting info for debugging at scale). Can be supplemented by some error tracking solution like http://getsentry.com.

I think above are P1's. Everything else is blocking event flow analysis but doesn't impact shell UX / overall event counts, so can be even lower than P2 (but then we shouldn't look at any metrics based on event flow).

**Comment by mikedotexe** [comment] 2020-05-22 18:16
@vgrichina when you say:
> Is there any reason to not do it automatically for every command

Do you mean instead of declaring all the keys like `eventtracking.EVENT_ID_DELETE_KEY_START`?

I see you point if that's what you mean.

Here's an image of the screen that I find most helpful in Mixpanel:
<img width="1042" alt="Screenshot 2020-05-22 10 36 00" src="https://user-images.githubusercontent.com/1042667/82694449-20b36f80-9c18-11ea-830b-c84ae71bec35.png">

The link is https://mixpanel.com/report/2144016/live
So this shows we are capturing the network, which is great. I'm personally opposed to sending their actual NEAR account, but am (of course) willing to have a conversation on that.
I also agree with you that we should add the operating system, as we know Windows support is getting better but don't know all the edge cases. We've also seen this with Linux, especially with `near login`. So yes, let's pass along the `process.platform` there. `darwin` is OS X, `linux` is all 'nix distros, and `win32` is Windows.

Next point, let's also add Mixpanel reports inside `catch` so that we're capturing failures.
Example: I faked it so that `near login` failed. I did this by running that command and then opening this in my browser: 
http://127.0.0.1:5000/?account_id=link.testnet&public_key=ed25519%3A9qBmLVy99KS8XYNwFYSuvMNM2t7KKYk84c5RNq3TLegR&all_keys=ed25519%3ABfGNmT4GXqLqLtWkFLNva2xHwLJfG9ZWYgU46cGgb5oz

Then near shell spits out the proper error:
>The account you provided [ link.testnet ] has not authorized the expected key [ ed25519:C2Aoxy... ]  Please try again.

Yet when I look in Mixpanel I see this:
<img width="925" alt="Screenshot 2020-05-22 11 12 16" src="https://user-images.githubusercontent.com/1042667/82697311-86562a80-9c1d-11ea-8701-479a783b0a56.png">

So we should comb the codebase for `try catch`es and make sure those are getting sent to Mixpanel. This is a false positive.

**Comment by mikedotexe** [comment] 2020-05-22 18:19
Also, I tested this branch on Windows and it works:
https://github.com/near/near-shell/tree/hotfix/mixpanel-crash-reporting

This needs to be cleaned up but will allow us to get rid of the stop-gap we have of "start" and "end" commands being recorded. So let's circle back on this.

**Comment by vgrichina** [comment] 2020-05-28 23:17
> Do you mean instead of declaring all the keys like eventtracking.EVENT_ID_DELETE_KEY_START?

yeah, I mean like we can have middleware which logs every command by default with a certain set of whitelisted options (to avoid leaking sensitive options accidentally). 

> I'm personally opposed to sending their actual NEAR account, but am (of course) willing to have a conversation on that.

If account actions were otherwise private I would agree with you. However basically every action besides view calls is persisted on chain by design. So it seems weird if we are more strict about collecting private opted-in analytics vs what is persisted on chain. 

> So we should comb the codebase for try catches and make sure those are getting sent to Mixpanel. This is a false positive.

**Comment by vgrichina** [comment] 2020-05-28 23:20
> Also, I tested this branch on Windows and it works:
> https://github.com/near/near-shell/tree/hotfix/mixpanel-crash-reporting
> 
> This needs to be cleaned up but will allow us to get rid of the stop-gap we have of "start" and "end" commands being recorded. So let's circle back on this.

yeah, let's make a PR.

it's a bit hacky but if it works on Windows and we don't have better alternative – should be fine

**Comment by janedegtiareva** [comment] 2020-07-14 17:24
Closing since metrics follow-up epic was completed.

**Closed** 2020-07-14 17:23 UTC
Labels: P2
