### ISSUE TITLE
Enhancement for near login

### ISSUE THREAD

**Issue by icerove** [near/near-shell#421] opened 2020-06-12 17:23 UTC
**Is your feature request related to a problem? Please describe.**
We are having different networks now like testnet, betanet and devnet. For the command `near login`, it has so many different setting in the config and when transferring network instead of using the default one, it is so inconvenient to change every setting. 
When we are in the near development, we can give the NEAR_ENV, but when we are not using the config file, there is no method to do so.

**Describe the solution you'd like**
given a flag like --network and assign mainnet, testnet, betanet and devnet to login to corresponding network   

**Additional context**
here is the options for `near login`:
Using options: {
  nodeUrl: 'https://rpc.testnet.near.org',
  networkId: 'default',
  contractName: undefined,
  walletUrl: 'https://wallet.testnet.near.org',
  helperUrl: 'https://helper.testnet.near.org',
  useLedgerKey: "44'/397'/0'/0'/1'",
  initialBalance: null
}

**Comment by janedegtiareva** [comment] 2020-06-12 17:36
The option already exists, and there is a known issue that it's not being applied in all the cases https://github.com/near/near-shell/issues/394. Does this address your concerns, or are there other improvements to consider?

**Comment by icerove** [comment] 2020-06-12 17:41
@janedegtiareva what option is that?

**Comment by janedegtiareva** [comment] 2020-06-12 20:04
networkId: 
(and it's a known issue that it's not working right now)
near login

logging in through NEAR protocol wallet

Options:
  --help                     Show help  [boolean]
  --version                  Show version number  [boolean]
  --nodeUrl, --node_url      NEAR node URL  [string] [default: "http://localhost:3030"]
  --networkId, --network_id  NEAR network ID, allows using different keys based on network  [string] [default: "default"]
  --helperUrl                NEAR contract helper URL  [string]
  --keyPath                  Path to master account key  [string]
  --accountId, --account_id  Unique identifier for the account  [string]

**Comment by chadoh** [comment] 2020-06-19 01:22
Seems like a duplicate of #394

**Closed by chadoh** 2020-06-19 01:22 UTC
Labels: enhancement
