### ISSUE TITLE
near create_account does not return hash of the transaction

### ISSUE THREAD

**Issue by nearmax** [near/near-shell#424] opened 2020-06-16 00:43 UTC
Try creating an account, e.g.:
```bash
near create_account bob.test.near --masterAccount test.near
```
Observe the output:
```
Using options: {
  masterAccount: 'test.near',
  networkId: 'local',
  nodeUrl: 'http://localhost:3030',
  contractName: 'myproject',
  walletUrl: 'https://wallet.testnet.near.org',
  helperUrl: 'https://helper.testnet.near.org',
  useLedgerKey: "44'/397'/0'/0'/1'",
  newLedgerKey: "44'/397'/0'/0'/1'",
  initialBalance: '100000000000000000000000000',
  accountId: 'bob.test.near'
}
Account bob.test.near for network "local" was created.
```
Observe that it does not output the hash of the transaction. Assuming some users use near-shell as their only interface with the blockchain it is unclear where do we expect them to learn the hashes of the transaction from. Recall, that hash of the transaction is required for various other commands, e.g. transaction status.

**Comment by chadoh** [comment] 2020-06-19 01:11
Duplicate of #410

**Closed by chadoh** 2020-06-19 01:11 UTC
Labels: bug
