### ISSUE TITLE
Strange error when querying account that doesn't exist

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-shell#350] opened 2020-05-05 19:19 UTC
To reproduce, try to do `near state somerandomaccount` with default environment, and it shows the `Error:  MethodNotAllowedError` instead of `AccountDoesNotExist`.

**Comment by bowenwang1996** [comment] 2020-05-05 19:21
Update: looks like there is some issue with redirecting the request from *.nearprotocol.com to *.near.org.

**Comment by potatodepaulo** [comment] 2020-05-12 17:49
This should be resolved by finishing url migration.

**Comment by chadoh** [comment] 2020-05-12 21:28
I believe this was caused by a temporary and mistakenly-added HTTP redirect from `rpc.*.nearprotocol.com` to `rpc.*.near.org`. Now that this has been removed, using config pointing to `nearprotocol.com` works correctly:

```
near state somerandomaccountlololol
Using options: {
  networkId: 'default',
  nodeUrl: 'https://rpc.testnet.nearprotocol.com',
  contractName: undefined,
  walletUrl: 'https://wallet.testnet.nearprotocol.com',
  helperUrl: 'https://helper.testnet.nearprotocol.com',
  accountId: 'somerandomaccountlololol',
  initialBalance: null
}
Error:  TypedError: [-32000] Server error: account somerandomaccountlololol does not exist while viewing
```

As does using `near.org`:

```
near state somerandomaccountlololol
Using options: {
  networkId: 'default',
  nodeUrl: 'https://rpc.testnet.near.org',
  contractName: undefined,
  walletUrl: 'https://wallet.testnet.near.org',
  helperUrl: 'https://helper.testnet.near.org',
  accountId: 'somerandomaccountlololol',
  initialBalance: null
}
Error:  TypedError: [-32000] Server error: account somerandomaccountlololol does not exist while viewing
```

**Closed by chadoh** 2020-05-12 21:28 UTC
Labels: P1, bug
