### ISSUE TITLE
Server error: Timeout (When transaction successful)

### ISSUE THREAD

**Issue by htafolla** [near/near-shell#399] opened 2020-06-04 15:08 UTC
When running commands in near shell you will receive a timeout error even though the transaction was successful.

Scheduling a call: blazenetio.stake({"amount": "30000000000000000000000000"})
Error: TypedError: [-32000] Server error: Timeout
at JsonRpcProvider.sendJsonRpc (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/providers/json-rpc-provider.js:129:27)

Scheduling a call: blazenetio.stake({"amount": "30000000000000000000000000"})
Error: GuestPanic [Error]: Smart contract panicked: panicked at 'Not enough unstaked balance to stake', src/lib.rs:279:9

View call: blazenetio.get_account_unstaked_balance({"account_id": "blaze2.betanet"})
'0'

View call: blazenetio.get_account_staked_balance({"account_id": "blaze2.betanet"})
'40000000000000000000000000'

**Comment by june07** [comment] 2020-06-07 20:02
Not able to duplicate this issue on my end, is the problem consistent for you...

set NODE_ENV=betanet&&node --inspect-brk=9267 bin\near call blazenetio stake "{\"amount\":\"1000000000000000000000000\"}" --accountId tester400.betanet 
Debugger listening on ws://127.0.0.1:9267/73b8e1ef-0ba2-4f3b-b527-4a090d76d226
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Using options: {
  accountId: 'tester400.betanet',
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: 'blazenetio',
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  useLedgerKey: "44'/397'/0'/0'/1'",
  gas: '100000000000000',
  amount: '0',
  methodName: 'stake',
  args: '{"amount":"1000000000000000000000000"}',
  initialBalance: null
}
Scheduling a call: blazenetio.stake({"amount":"1000000000000000000000000"})
[blazenetio]: @tester400.betanet staking 999999999999999999999999. Received 999999998999238686151034 new staking shares. Total 1000000000000000000000001 unstaked balance and 999999998999238686151034 staking shares
[blazenetio]: Contract total staked balance is 101000000109036815839400000. Total number of shares 101000000007959923031534608

**Comment by htafolla** [comment] 2020-06-08 18:56
@june07 I believe this happens when the network is stalling or not enough nodes are online. I have not seen it since @bowenwang1996 did the last hard-fork.

**Comment by bowenwang1996** [comment] 2020-06-08 22:53
Duplicate of https://github.com/near/near-api-js/issues/127

**Closed by bowenwang1996** 2020-06-08 22:53 UTC
Labels: bug
